[project]
name = "automacro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dxcam>=0.0.5",
    "onnxruntime>=1.23.2",
    "opencv-python>=4.13.0.92",
    "pyclipper>=1.4.0",
    "pygetwindow>=0.0.9",
    "pynput>=1.8.1",
    "pywin32>=311",
    "scikit-image>=0.26.0",
    "shapely>=2.1.2",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
